repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    - id: fmt
  - repo: local
    hooks:
    # Split clippy command into two parts, because `--fix` suppress the "warning to error" conversion.
    - id: clipper-fixlint
      name: clipper-fixlint
      language: system
      files: '\.rs$'
      entry: cargo clippy --all-targets --fix --allow-dirty --allow-staged
      pass_filenames: false
    - id: clipper-check
      name: clipper-check
      language: system
      files: '\.rs$'
      entry: cargo clippy --all-targets -- -D warnings
      pass_filenames: false
