[package]
name = "moonlink_backend"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
moonlink = { path = "../moonlink" }
moonlink_connectors = { path = "../moonlink_connectors" }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio-postgres = { workspace = true }
