[package]
name = "moonlink_backend"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
profiling = []

[dependencies]
arrow-array.workspace = true
console-subscriber = { workspace = true }
moonlink = { path = "../moonlink", features = ["test-utils"] }
moonlink_connectors = { path = "../moonlink_connectors" }
moonlink_metadata_store = { path = "../moonlink_metadata_store" }
more-asserts = { workspace = true }
nix = { workspace = true }
parquet = { workspace = true, features = ["arrow"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
iceberg = { workspace = true }
roaring = { workspace = true }
serial_test = { workspace = true }
tempfile = { workspace = true }
tokio-postgres = { workspace = true }
