[package]
name = "moonlink"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
tokio.workspace = true
arrow.workspace = true
thiserror.workspace = true
parquet.workspace = true
uuid.workspace = true
futures.workspace = true
multimap.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
iceberg.workspace = true
iceberg-catalog-rest.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
